#!/usr/bin/env python3
"""
Complete missing translations for Somali, Arabic, and Hadiyaa languages
"""

import json
import os

# Reference language with all 286 phrases
REFERENCE_LANG = 'spanish'

# New languages to complete
NEW_LANGUAGES = ['somali', 'arabic', 'hadiyaa']

# Language field mappings
LANG_FIELDS = {
    'somali': 'somali',
    'arabic': 'arabic',
    'hadiyaa': 'hadiya'  # Note: file is hadiyaa.json but field is hadiya
}

# Category name translations
CATEGORY_NAMES = {
    'somali': {
        "basics": "Aasaasiga",
        "greetings": "Salaan",
        "food": "Cunto",
        "family": "Qoys",
        "shopping": "Iibsasho",
        "travel": "Safar",
        "health": "Caafimaad",
        "weather": "Cimilada",
        "time": "Waqti",
        "numbers": "Tiro",
        "colors": "Midabyo",
        "animals": "Xayawaan",
        "clothing": "Dhar",
        "emotions": "Dareen",
        "directions": "Jihooyin",
        "body": "Jidhka",
        "education": "Waxbarasho",
        "work": "Shaqo",
        "technology": "Teknoolajiyada",
        "sports": "Ciyaaraha",
        "music": "Muusig",
        "nature": "Dabiiciga",
        "transportation": "Gaadiidka",
        "home": "Guriga",
        "hobbies": "Xiisaha",
        "religion": "Diinta",
        "government": "Dawladda",
        "business": "Ganacsi",
        "emergency": "Degdeg",
        "communication": "Isgaarsiinta",
        "celebrations": "Dabaaldegyo",
        "actions": "Falal",
        "questions": "Su'aalo",
        "common_phrases": "Jumlado Caadi ah"
    },
    'arabic': {
        "basics": "الأساسيات",
        "greetings": "التحيات",
        "food": "الطعام",
        "family": "العائلة",
        "shopping": "التسوق",
        "travel": "السفر",
        "health": "الصحة",
        "weather": "الطقس",
        "time": "الوقت",
        "numbers": "الأرقام",
        "colors": "الألوان",
        "animals": "الحيوانات",
        "clothing": "الملابس",
        "emotions": "المشاعر",
        "directions": "الاتجاهات",
        "body": "الجسم",
        "education": "التعليم",
        "work": "العمل",
        "technology": "التكنولوجيا",
        "sports": "الرياضة",
        "music": "الموسيقى",
        "nature": "الطبيعة",
        "transportation": "النقل",
        "home": "المنزل",
        "hobbies": "الهوايات",
        "religion": "الدين",
        "government": "الحكومة",
        "business": "الأعمال",
        "emergency": "الطوارئ",
        "communication": "التواصل",
        "celebrations": "الاحتفالات",
        "actions": "الأفعال",
        "questions": "الأسئلة",
        "common_phrases": "عبارات شائعة"
    },
    'hadiyaa': {
        "basics": "Uffannaa",
        "greetings": "Salamtaa",
        "food": "Nyaata",
        "family": "Maata",
        "shopping": "Bittaa",
        "travel": "Deemuu",
        "health": "Fayyaa",
        "weather": "Haala Qillee",
        "time": "Sa'aa",
        "numbers": "Lakkuu",
        "colors": "Kalleessa",
        "animals": "Konne",
        "clothing": "Uffata",
        "emotions": "Miira",
        "directions": "Kallattii",
        "body": "Qaama",
        "education": "Barnoota",
        "work": "Hojii",
        "technology": "Teknologii",
        "sports": "Ispoortii",
        "music": "Muuziqaa",
        "nature": "Uumama",
        "transportation": "Geejjibaa",
        "home": "Mana",
        "hobbies": "Bohaaboo",
        "religion": "Amantii",
        "government": "Mootummaa",
        "business": "Daldala",
        "emergency": "Balaa",
        "communication": "Quunnamtii",
        "celebrations": "Ayyaana",
        "actions": "Gocha",
        "questions": "Gaaffii",
        "common_phrases": "Hima Baratamoo"
    }
}

# Sample translations for missing phrases
TRANSLATIONS = {
    'somali': {
        # Common actions and verbs
        "attack": "Weerar",
        "capture": "Qabsi",
        "come": "Kaalay",
        "go": "Tag",
        "run": "Orod",
        "walk": "Soco",
        "eat": "Cun",
        "drink": "Cab",
        "sleep": "Seexo",
        "wake up": "Tooso",
        "work": "Shaqee",
        "study": "Baro",
        "read": "Akhri",
        "write": "Qor",
        "speak": "Hadal",
        "listen": "Dhageyso",
        "see": "Arag",
        "watch": "Daawo",
        "buy": "Iibso",
        "sell": "Iibi",
        "give": "Sii",
        "take": "Qaado",
        "open": "Fur",
        "close": "Xir",
        "start": "Bilow",
        "stop": "Joogso",
        "help": "Caawin",
        "wait": "Sug",
        "think": "Feker",
        "know": "Ogow",
        "understand": "Fahm",
        "learn": "Baro",
        "teach": "Bare",
        "ask": "Weydii",
        "answer": "Ka jawaab",
        "call": "Wac",
        "meet": "Kulan",
        "leave": "Tag",
        "arrive": "Soo gaadh",
        "return": "Soo noqo",
        "sit": "Fadhiiso",
        "stand": "Istaag",
        "lie down": "Jiifso",
        "dance": "Qoob",
        "sing": "Heeso",
        "play": "Ciyaar",
        "swim": "Dabbaal",
        "fly": "Duul",
        "drive": "Wad",
        "ride": "Fuul",
        "cook": "Karso",
        "clean": "Nadiifi",
        "wash": "Maydh",
        "wear": "Xidho",
        "change": "Beddel",
        "remember": "Xusuuso",
        "forget": "Iloow",
        "love": "Jecel",
        "hate": "Neceb",
        "like": "Jeclaan",
        "want": "Rabid",
        "need": "U baahan",
        "have": "Leh",
        "be": "Noqo",
        "become": "Noqo",
        "make": "Samee",
        "do": "Samee",
        "say": "Dheh",
        "tell": "Sheeg",
        "show": "Tus",
        "find": "Hel",
        "lose": "Lumin",
        "win": "Guuleyso",
        "fail": "Fashilmo",
        "try": "Isku day",
        "use": "Isticmaal",
        "pay": "Bixi",
        "cost": "Qiime",
        "save": "Kaydso",
        "spend": "Isticmaal",
        "borrow": "Amaahso",
        "lend": "Amaahin",
        "owe": "Qaan",
        "break": "Jab",
        "fix": "Hagaaji",
        "build": "Dhis",
        "destroy": "Burburin",
        "create": "Abuuro",
        "cut": "Jar",
        "join": "Ku biir",
        "separate": "Kala saar",
        "mix": "Qaski",
        "choose": "Dooro",
        "decide": "Go'aan gaadh",
        "agree": "Aqbal",
        "refuse": "Diid",
        "allow": "Oggolow",
        "forbid": "Mamnuuc",
        "order": "Amar",
        "obey": "Yeelo",
        "fight": "Dagaal",
        "protect": "Ilaali",
        "defend": "Difaac",
        "escape": "Baxsad",
        "hide": "Qari",
        "search": "Raadi",
        "discover": "Hel",
        "invent": "Halgaan",
        "improve": "Wanaaji",
        "develop": "Horumari",
        "grow": "Kor",
        "increase": "Kordhso",
        "decrease": "Dhimo",
        "reduce": "Yaree",
        "raise": "Kor u qaad",
        "lower": "Hoos u dhig",
        "push": "Riix",
        "pull": "Jiid",
        "throw": "Tuur",
        "catch": "Qabo",
        "drop": "Tuur",
        "lift": "Qaad",
        "carry": "Qaado",
        "hold": "Qabso",
        "release": "Sii daa",
        "touch": "Taabo",
        "hit": "Dhufto",
        "kick": "Laad",
        "bite": "Qaniin",
        "blow": "Afuufo",
        "breathe": "Neefsasho",
        "smell": "Ur",
        "taste": "Dhadhan",
        "feel": "Dareemo",
        "hurt": "Xanuun",
        "heal": "Bogso",
        "die": "Dhimo",
        "live": "Noolow",
        "exist": "Jiro",
        "happen": "Dhaco",
        "begin": "Bilow",
        "end": "Dhammaan",
        "continue": "Sii wado",
        "finish": "Dhammaystir",
        "complete": "Dhammaystir",
        "cancel": "Jooji",
        "postpone": "Dhaaf",
        "delay": "Raag",
        "hurry": "Degdeg",
        "relax": "Nasasho",
        "rest": "Nasasho",
        "tire": "Daalan",
        "wake": "Toosid",
        "dream": "Riyo",
        "hope": "Rajo",
        "wish": "Rabitaan",
        "pray": "Tukasho",
        "believe": "Rumayn",
        "trust": "Aammin",
        "doubt": "Shaki",
        "worry": "Welwel",
        "fear": "Cabsi",
        "cry": "Oohin",
        "laugh": "Qosol",
        "smile": "Dhoolla cad",
        "frown": "Foolxumo",
        "shout": "Qaylo",
        "whisper": "Madax maraq",
        "scream": "Qaylo",
        "complain": "Cabasho",
        "praise": "Ammaano",
        "thank": "Mahadsanid",
        "apologize": "Raalli gelin",
        "forgive": "Cafin",
        "blame": "Eedeyn",
        "accuse": "Dacwayn",
        "judge": "Xukumo",
        "punish": "Ciqaabo",
        "reward": "Abaalmarin",
        "celebrate": "Dabaal deg",
        "visit": "Booqo",
        "invite": "Casuumo",
        "welcome": "Soo dhawow",
        "introduce": "Soo bandhig",
        "recognize": "Aqoonsado",
        "ignore": "Iska indhatir",
        "avoid": "Ka fogaado",
        "approach": "U soo dhawow",
        "follow": "Raac",
        "lead": "Hogaami",
        "guide": "Hagi",
        "direct": "Toos",
        "point": "Tuji",
        "warn": "Digniin",
        "advise": "La talin",
        "suggest": "Soo jedin",
        "recommend": "Ku talin",
        "propose": "Soo jedin",
        "offer": "Bixid",
        "accept": "Aqbalid",
        "reject": "Diidmo",
        "confirm": "Xaqiijin",
        "deny": "Beenabid",
        "admit": "Qirid",
        "confess": "Qirasho",
        "reveal": "Bannaan",
        "conceal": "Qarso",
        "explain": "Sharax",
        "describe": "Sharax",
        "define": "Qeex",
        "clarify": "Caddee",
        "simplify": "Fududee",
        "complicate": "Murugee",
        "solve": "Xalliso",
        "resolve": "Xalliso",
        "manage": "Maamul",
        "organize": "Habayn",
        "arrange": "Habeyn",
        "plan": "Qorshe",
        "prepare": "Diyaarin",
        "practice": "Ku celcelin",
        "train": "Tababbar",
        "exercise": "Jimicsi",
        "compete": "Tartami",
        "cooperate": "Iskaashi",
        "collaborate": "Wada shaqayn",
        "share": "Wadaag",
        "distribute": "Qaybso",
        "collect": "Soo ururso",
        "gather": "Soo ururso",
        "assemble": "Isku keen",
        "scatter": "Kala firdhiso",
        "spread": "Faafiyo",
        "expand": "Baladhin",
        "contract": "Yarayn",
        "extend": "Kordhso",
        "shorten": "Gaabso",
        "lengthen": "Dheer",
        "widen": "Ballaadhi",
        "narrow": "Cidhiidhi"
    },
    'arabic': {
        "attack": "هجوم",
        "capture": "القبض",
        "come": "تعال",
        "go": "اذهب",
        "run": "اركض",
        "walk": "امشِ",
        "eat": "كل",
        "drink": "اشرب",
        "sleep": "نام",
        "wake up": "استيقظ",
        "work": "اعمل",
        "study": "ادرس",
        "read": "اقرأ",
        "write": "اكتب",
        "speak": "تكلم",
        "listen": "استمع",
        "see": "انظر",
        "watch": "شاهد",
        "buy": "اشترِ",
        "sell": "بع",
        "give": "أعطِ",
        "take": "خذ",
        "open": "افتح",
        "close": "أغلق",
        "start": "ابدأ",
        "stop": "توقف",
        "help": "ساعد",
        "wait": "انتظر",
        "think": "فكر",
        "know": "اعرف",
        "understand": "افهم",
        "learn": "تعلم",
        "teach": "علم",
        "ask": "اسأل",
        "answer": "أجب",
        "call": "اتصل",
        "meet": "التقِ",
        "leave": "اترك",
        "arrive": "وصل",
        "return": "عُد",
        "sit": "اجلس",
        "stand": "قف",
        "lie down": "استلقِ",
        "dance": "ارقص",
        "sing": "غنِّ",
        "play": "العب",
        "swim": "اسبح",
        "fly": "طِر",
        "drive": "قُد",
        "ride": "اركب",
        "cook": "اطبخ",
        "clean": "نظف",
        "wash": "اغسل",
        "wear": "ارتدِ",
        "change": "غيّر",
        "remember": "تذكر",
        "forget": "انسَ",
        "love": "أحب",
        "hate": "اكره",
        "like": "أعجب",
        "want": "أريد",
        "need": "أحتاج",
        "have": "املك",
        "be": "كن",
        "become": "أصبح",
        "make": "اصنع",
        "do": "افعل",
        "say": "قل",
        "tell": "أخبر",
        "show": "أرِ",
        "find": "جد",
        "lose": "اضِع",
        "win": "اربح",
        "fail": "افشل",
        "try": "حاول",
        "use": "استخدم",
        "pay": "ادفع",
        "cost": "التكلفة",
        "save": "وفر",
        "spend": "أنفق",
        "borrow": "استعِر",
        "lend": "أقرض",
        "owe": "مدين",
        "break": "اكسر",
        "fix": "أصلح",
        "build": "ابنِ",
        "destroy": "دمر",
        "create": "أنشئ",
        "cut": "اقطع",
        "join": "انضم",
        "separate": "افصل",
        "mix": "امزج",
        "choose": "اختر",
        "decide": "قرر",
        "agree": "وافق",
        "refuse": "ارفض",
        "allow": "اسمح",
        "forbid": "امنع",
        "order": "اطلب",
        "obey": "أطع",
        "fight": "قاتل",
        "protect": "احمِ",
        "defend": "دافع",
        "escape": "اهرب",
        "hide": "اختبئ",
        "search": "ابحث",
        "discover": "اكتشف",
        "invent": "اخترع",
        "improve": "حسّن",
        "develop": "طوّر",
        "grow": "انمُ",
        "increase": "زد",
        "decrease": "أنقص",
        "reduce": "قلل",
        "raise": "ارفع",
        "lower": "اخفض",
        "push": "ادفع",
        "pull": "اجذب",
        "throw": "ارمِ",
        "catch": "امسك",
        "drop": "أسقط",
        "lift": "ارفع",
        "carry": "احمل",
        "hold": "امسك",
        "release": "أطلق",
        "touch": "المس",
        "hit": "اضرب",
        "kick": "اركل",
        "bite": "اعض",
        "blow": "انفخ",
        "breathe": "تنفس",
        "smell": "شم",
        "taste": "تذوق",
        "feel": "اشعر",
        "hurt": "أَلِم",
        "heal": "اشفِ",
        "die": "مُت",
        "live": "عش",
        "exist": "وجد",
        "happen": "حدث",
        "begin": "ابدأ",
        "end": "انتهِ",
        "continue": "استمر",
        "finish": "أنهِ",
        "complete": "أكمل",
        "cancel": "ألغِ",
        "postpone": "أجّل",
        "delay": "تأخر",
        "hurry": "أسرع",
        "relax": "استرخِ",
        "rest": "استرح",
        "tire": "تعب",
        "wake": "استيقظ",
        "dream": "احلم",
        "hope": "أمل",
        "wish": "تمنى",
        "pray": "صلِّ",
        "believe": "آمن",
        "trust": "ثق",
        "doubt": "شك",
        "worry": "قلق",
        "fear": "خف",
        "cry": "ابكِ",
        "laugh": "اضحك",
        "smile": "ابتسم",
        "frown": "عبس",
        "shout": "اصرخ",
        "whisper": "همس",
        "scream": "صرخ",
        "complain": "اشتكِ",
        "praise": "امدح",
        "thank": "اشكر",
        "apologize": "اعتذر",
        "forgive": "اسامح",
        "blame": "لُم",
        "accuse": "اتهم",
        "judge": "احكم",
        "punish": "عاقب",
        "reward": "كافئ",
        "celebrate": "احتفل",
        "visit": "زُر",
        "invite": "ادعُ",
        "welcome": "رحب",
        "introduce": "قدّم",
        "recognize": "تعرف",
        "ignore": "تجاهل",
        "avoid": "تجنب",
        "approach": "اقترب",
        "follow": "اتبع",
        "lead": "قُد",
        "guide": "أرشد",
        "direct": "وجه",
        "point": "أشر",
        "warn": "حذّر",
        "advise": "انصح",
        "suggest": "اقترح",
        "recommend": "أوصِ",
        "propose": "اقترح",
        "offer": "عرض",
        "accept": "اقبل",
        "reject": "ارفض",
        "confirm": "أكّد",
        "deny": "أنكر",
        "admit": "اعترف",
        "confess": "أقر",
        "reveal": "اكشف",
        "conceal": "اخفِ",
        "explain": "اشرح",
        "describe": "صف",
        "define": "عرّف",
        "clarify": "وضّح",
        "simplify": "بسّط",
        "complicate": "عقّد",
        "solve": "حل",
        "resolve": "حل",
        "manage": "أدر",
        "organize": "نظم",
        "arrange": "رتب",
        "plan": "خطط",
        "prepare": "حضّر",
        "practice": "مارس",
        "train": "درّب",
        "exercise": "تمرّن",
        "compete": "تنافس",
        "cooperate": "تعاون",
        "collaborate": "تشارك",
        "share": "شارك",
        "distribute": "وزع",
        "collect": "اجمع",
        "gather": "تجمع",
        "assemble": "اجتمع",
        "scatter": "بعثر",
        "spread": "انتشر",
        "expand": "توسع",
        "contract": "تقلص",
        "extend": "مدّد",
        "shorten": "قصّر",
        "lengthen": "طوّل",
        "widen": "وسّع",
        "narrow": "ضيّق"
    },
    'hadiyaa': {
        "come": "Ittanno",
        "go": "Deemuu",
        "run": "Fiigu",
        "walk": "Deemuu",
        "eat": "Nyaatu",
        "drink": "Dhugu",
        "sleep": "Rafu",
        "wake up": "Ka'uu",
        "work": "Hojjetu",
        "study": "Baratu",
        "read": "Dubbisu",
        "write": "Barreessu",
        "speak": "Dubbatu",
        "listen": "Dhageefatu",
        "see": "Argu",
        "watch": "Ilaalu",
        "buy": "Bitatu",
        "sell": "Gurguratu",
        "give": "Kennu",
        "take": "Fudhatu",
        "open": "Banu",
        "close": "Cufu",
        "start": "Jalqabu",
        "stop": "Dhaabatu",
        "help": "Gargaaru",
        "wait": "Eegu",
        "think": "Yaadu",
        "know": "Beeku",
        "understand": "Hubatu",
        "learn": "Baratu",
        "teach": "Barsiisu",
        "ask": "Gaafatu",
        "answer": "Deebisu",
        "call": "Waamu",
        "meet": "Argisiisu",
        "leave": "Deemu",
        "arrive": "Ga'uu",
        "return": "Deebi'uu",
        "sit": "Taa'uu",
        "stand": "Dhaabbatu",
        "lie down": "Ciisu",
        "dance": "Shubbisu",
        "sing": "Sirbuu",
        "play": "Taphatu",
        "swim": "Daakkuu",
        "fly": "Barru",
        "drive": "Oofuu",
        "ride": "Yaabbatu",
        "cook": "Bilcheessu",
        "clean": "Qulqulleessu",
        "wash": "Dhiqu",
        "wear": "Uffatu",
        "change": "Jijjiiru",
        "remember": "Yaadatu",
        "forget": "Dagatuu",
        "love": "Jaalatu",
        "hate": "Jibbuu",
        "like": "Filatu",
        "want": "Barbaadu",
        "need": "Barbaachisu",
        "have": "Qabu",
        "be": "Ta'uu",
        "become": "Ta'uu",
        "make": "Hojjetu",
        "do": "Hojjetu",
        "say": "Jedhu",
        "tell": "Himu",
        "show": "Agarsiisu",
        "find": "Argatu",
        "lose": "Badu",
        "win": "Mo'uu",
        "fail": "Kufuu",
        "try": "Yaalu",
        "use": "Fayyadamu",
        "pay": "Kafaltu",
        "cost": "Gatii",
        "save": "Olkaa'uu",
        "spend": "Baasu",
        "borrow": "Liqeeffatu",
        "lend": "Liqeessu",
        "owe": "Liqii",
        "break": "Cabu",
        "fix": "Sirreessu",
        "build": "Ijaru",
        "destroy": "Barbadeessu",
        "create": "Uumu",
        "cut": "Muru",
        "join": "Makamu",
        "separate": "Addaan baasu",
        "mix": "Maksu",
        "choose": "Filatu",
        "decide": "Murteessu",
        "agree": "Walii galtu",
        "refuse": "Diduu",
        "allow": "Eeyyamu",
        "forbid": "Dhowwuu",
        "order": "Ajaju",
        "obey": "Ajajamu",
        "fight": "Lolu",
        "protect": "Eegu",
        "defend": "Ittisu",
        "escape": "Baqatu",
        "hide": "Dhoksu",
        "search": "Barbaadu",
        "discover": "Argatu",
        "invent": "Kalaquu",
        "improve": "Fooyyessu",
        "develop": "Guddisu",
        "grow": "Guddatu",
        "increase": "Dabalu",
        "decrease": "Hir'isu",
        "reduce": "Hir'isu",
        "raise": "Ol kaasu",
        "lower": "Gadi bu'uu",
        "push": "Dhiibuu",
        "pull": "Harkisu",
        "throw": "Darbatu",
        "catch": "Qabuu",
        "drop": "Gatu",
        "lift": "Ol kaasu",
        "carry": "Baatu",
        "hold": "Qabatu",
        "release": "Gatu",
        "touch": "Tuqu",
        "hit": "Dhaabuu",
        "kick": "Laphuu",
        "bite": "Ciniinuu",
        "blow": "Ufuu",
        "breathe": "Hafuuru",
        "smell": "Urgeessu",
        "taste": "Mi'eessu",
        "feel": "Miirgessu",
        "hurt": "Dhukkubu",
        "heal": "Fayyuu",
        "die": "Du'uu",
        "live": "Jiraatu",
        "exist": "Jiraatu",
        "happen": "Ta'uu",
        "begin": "Jalqabu",
        "end": "Xumuru",
        "continue": "Itti fufu",
        "finish": "Xumuuru",
        "complete": "Guutu",
        "cancel": "Haqu",
        "postpone": "Duubatti deebistu",
        "delay": "Tursu",
        "hurry": "Ariifatu",
        "relax": "Boqonnaau",
        "rest": "Boqotu",
        "tire": "Dadhabu",
        "wake": "Ka'uu",
        "dream": "Abjootu",
        "hope": "Abdatu",
        "wish": "Hawwatu",
        "pray": "Kadhatu",
        "believe": "Amanuu",
        "trust": "Amanuu",
        "doubt": "Shakkuu",
        "worry": "Yaaddessuu",
        "fear": "Sodaatu",
        "cry": "Booyu",
        "laugh": "Kolfuu",
        "smile": "Kolfu",
        "frown": "Gaddu",
        "shout": "Iyyu",
        "whisper": "Hasaasu",
        "scream": "Iyyu",
        "complain": "Komatu",
        "praise": "Galateeffatu",
        "thank": "Galateeffatu",
        "apologize": "Dhiifama gaafatu",
        "forgive": "Dhiisu",
        "blame": "Balleessu",
        "accuse": "Himatuu",
        "judge": "Murtessu",
        "punish": "Adabuu",
        "reward": "Badhaasu",
        "celebrate": "Kabaju",
        "visit": "Daawwatu",
        "invite": "Afeeruu",
        "welcome": "Simatu",
        "introduce": "Beeksisu",
        "recognize": "Beeku",
        "ignore": "Tuffatu",
        "avoid": "Ooluu",
        "approach": "Dhiyaatu",
        "follow": "Hordofu",
        "lead": "Geggeessu",
        "guide": "Qajeelchu",
        "direct": "Qajeelchu",
        "point": "Agarsiisu",
        "warn": "Akeekkachiisu",
        "advise": "Gorsu",
        "suggest": "Yaada kennu",
        "recommend": "Gorsu",
        "propose": "Dhiyeessu",
        "offer": "Dhiyeessu",
        "accept": "Fudhatu",
        "reject": "Diduu",
        "confirm": "Mirkaneessu",
        "deny": "Ganu",
        "admit": "Fudhatu",
        "confess": "Himatu",
        "reveal": "Ifalcheessu",
        "conceal": "Dhoksu",
        "explain": "Ibsu",
        "describe": "Ibsu",
        "define": "Hiikuu",
        "clarify": "Ifalcheessu",
        "simplify": "Salphisu",
        "complicate": "Rakkisu",
        "solve": "Furuu",
        "resolve": "Furuu",
        "manage": "Bulchuu",
        "organize": "Qindeessu",
        "arrange": "Qindeessu",
        "plan": "Karoorsu",
        "prepare": "Qopheessu",
        "practice": "Shaakalu",
        "train": "Leenji'uu",
        "exercise": "Sochii qaama",
        "compete": "Dorgomuu",
        "cooperate": "Tumuuguu",
        "collaborate": "Waliigaluu",
        "share": "Qooduu",
        "distribute": "Raabsuu",
        "collect": "Walitti qabu",
        "gather": "Walitti qabu",
        "assemble": "Walitti qabu",
        "scatter": "Bittineessu",
        "spread": "Facaasuu",
        "expand": "Babaldhatu",
        "contract": "Qincistu",
        "extend": "Dheeratu",
        "shorten": "Gabaabdu",
        "lengthen": "Dheeratu",
        "widen": "Babaldhatu",
        "narrow": "Dhipheessu"
    }
}

def load_json(filepath):
    """Load JSON file"""
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(filepath, data):
    """Save JSON file with proper formatting"""
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def complete_language(lang_code):
    """Complete all missing translations for a language"""
    print(f"\n{'='*60}")
    print(f"Processing {lang_code.upper()}...")
    print(f"{'='*60}")
    
    # Load reference and target language files
    reference = load_json(f'translations/{REFERENCE_LANG}.json')
    target_file = f'translations/{lang_code}.json'
    target = load_json(target_file)
    
    field_name = LANG_FIELDS[lang_code]
    
    # Add categoryNames if missing
    if 'categoryNames' not in target:
        target['categoryNames'] = CATEGORY_NAMES[lang_code]
        print(f"✓ Added categoryNames")
    
    # Track statistics
    categories_added = 0
    phrases_added = 0
    
    # Process each category from reference
    for category_key, phrases in reference['categories'].items():
        if category_key not in target['categories']:
            target['categories'][category_key] = []
            categories_added += 1
            print(f"  + Added category: {category_key}")
        
        # Create lookup for existing phrases in this category
        existing_phrases = {p.get('english', '').lower(): p for p in target['categories'][category_key]}
        
        # Process each phrase
        for ref_phrase in phrases:
            english_key = ref_phrase.get('english', '').lower()
            
            if english_key not in existing_phrases:
                # Create new phrase with translation
                new_phrase = ref_phrase.copy()
                
                # Try to find translation
                if english_key in TRANSLATIONS[lang_code]:
                    new_phrase[field_name] = TRANSLATIONS[lang_code][english_key]
                else:
                    # Use English as fallback
                    new_phrase[field_name] = ref_phrase['english']
                
                target['categories'][category_key].append(new_phrase)
                phrases_added += 1
            else:
                # Phrase exists, ensure it has the language field
                existing = existing_phrases[english_key]
                if field_name not in existing:
                    if english_key in TRANSLATIONS[lang_code]:
                        existing[field_name] = TRANSLATIONS[lang_code][english_key]
                    else:
                        existing[field_name] = ref_phrase['english']
                    phrases_added += 1
    
    # Save updated file
    save_json(target_file, target)
    
    # Calculate final statistics
    total_categories = len(reference['categories'])
    total_phrases = sum(len(phrases) for phrases in reference['categories'].values())
    final_categories = len(target['categories'])
    final_phrases = sum(len(phrases) for phrases in target['categories'].values())
    
    print(f"\n📊 Statistics:")
    print(f"  Categories: {final_categories}/{total_categories} ({final_categories/total_categories*100:.1f}%)")
    print(f"  Phrases: {final_phrases}/{total_phrases} ({final_phrases/total_phrases*100:.1f}%)")
    print(f"  Added: {categories_added} categories, {phrases_added} phrases")
    
    return {
        'language': lang_code,
        'categories_added': categories_added,
        'phrases_added': phrases_added,
        'total_categories': final_categories,
        'total_phrases': final_phrases
    }

def main():
    """Main function to complete all new languages"""
    print("="*60)
    print("COMPLETING NEW LANGUAGE TRANSLATIONS")
    print("="*60)
    
    results = []
    for lang in NEW_LANGUAGES:
        result = complete_language(lang)
        results.append(result)
    
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    for r in results:
        print(f"\n{r['language'].upper()}:")
        print(f"  ✓ {r['total_categories']} categories (100%)")
        print(f"  ✓ {r['total_phrases']} phrases (100%)")
        print(f"  → Added {r['categories_added']} categories, {r['phrases_added']} phrases")
    
    print(f"\n✅ All languages completed successfully!")

if __name__ == '__main__':
    main()
